In [1]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split, GridSearchCV
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data = load_breast_cancer()
X, y = load_breast_cancer(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [2]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression()
clf.fit(X_train, y_train)


c:\users\user\appdata\local\programs\python\python37\lib\site-packages\sklearn\linear_model\_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [3]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

y_pred = clf.predict(X_test)
print("testing set")
print("accurcy: %f" % accuracy_score(y_test, y_pred))
print("precision: %f" % precision_score(y_test, y_pred, zero_division=0))
print("recall: %f" % recall_score(y_test, y_pred))
print("f1 scorce: %f" % f1_score(y_test, y_pred))
print("confusion matrix:\n", confusion_matrix(y_test, y_pred))
y_pred = clf.predict(X_train)
print("\ntraining set")
print("accurcy: %f" % accuracy_score(y_train, y_pred))
print("precision: %f" % precision_score(y_train, y_pred, zero_division=0))
print("recall: %f" % recall_score(y_train, y_pred))
print("f1 scorce: %f" % f1_score(y_train, y_pred))
print("confusion matrix:\n", confusion_matrix(y_train, y_pred))

testing set
accurcy: 0.970760
precision: 0.963964
recall: 0.990741
f1 scorce: 0.977169
confusion matrix:
 [[ 59   4]
 [  1 107]]

training set
accurcy: 0.939698
precision: 0.944664
recall: 0.959839
f1 scorce: 0.952191
confusion matrix:
 [[135  14]
 [ 10 239]]


In [4]:
clf = LogisticRegression(penalty='l1', solver='liblinear')
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
print("testing set")
print("accurcy: %f" % accuracy_score(y_test, y_pred))
print("precision: %f" % precision_score(y_test, y_pred, zero_division=0))
print("recall: %f" % recall_score(y_test, y_pred))
print("f1 scorce: %f" % f1_score(y_test, y_pred))
print("confusion matrix:\n", confusion_matrix(y_test, y_pred))
y_pred = clf.predict(X_train)
print("\ntraining set")
print("accurcy: %f" % accuracy_score(y_train, y_pred))
print("precision: %f" % precision_score(y_train, y_pred, zero_division=0))
print("recall: %f" % recall_score(y_train, y_pred))
print("f1 scorce: %f" % f1_score(y_train, y_pred))
print("confusion matrix:\n", confusion_matrix(y_train, y_pred))

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\sklearn\svm\_base.py:986: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


testing set
accurcy: 0.959064
precision: 0.963303
recall: 0.972222
f1 scorce: 0.967742
confusion matrix:
 [[ 59   4]
 [  3 105]]

training set
accurcy: 0.954774
precision: 0.952941
recall: 0.975904
f1 scorce: 0.964286
confusion matrix:
 [[137  12]
 [  6 243]]


In [6]:
clf = LogisticRegression(penalty='l2', solver='liblinear')
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
print("testing set")
print("accurcy: %f" % accuracy_score(y_test, y_pred))
print("precision: %f" % precision_score(y_test, y_pred, zero_division=0))
print("recall: %f" % recall_score(y_test, y_pred))
print("f1 scorce: %f" % f1_score(y_test, y_pred))
print("confusion matrix:\n", confusion_matrix(y_test, y_pred))
y_pred = clf.predict(X_train)
print("\ntraining set")
print("accurcy: %f" % accuracy_score(y_train, y_pred))
print("precision: %f" % precision_score(y_train, y_pred, zero_division=0))
print("recall: %f" % recall_score(y_train, y_pred))
print("f1 scorce: %f" % f1_score(y_train, y_pred))
print("confusion matrix:\n", confusion_matrix(y_train, y_pred))

testing set
accurcy: 0.964912
precision: 0.963636
recall: 0.981481
f1 scorce: 0.972477
confusion matrix:
 [[ 59   4]
 [  2 106]]

training set
accurcy: 0.952261
precision: 0.952756
recall: 0.971888
f1 scorce: 0.962227
confusion matrix:
 [[137  12]
 [  7 242]]


In [5]:
logreg = LogisticRegression(random_state=121)
param_grid = {
    'penalty': ['l1', 'l2', 'elasticnet'],
    'C': [0.01, 0.05, 0.1, 0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1,2,3,4,5,6,7,8,9,10,12,13,14,15,16,16.5,17,18],
    'solver': ['liblinear','saga']}
model = GridSearchCV(logreg, param_grid=param_grid, scoring='accuracy', cv=10, n_jobs=-1)

model.fit(X_train, y_train)

print('Best Params:', model.best_params_)

Best Params: {'C': 15, 'penalty': 'l1', 'solver': 'liblinear'}


c:\users\user\appdata\local\programs\python\python37\lib\site-packages\sklearn\model_selection\_search.py:921: UserWarning: One or more of the test scores are non-finite: [0.90955128 0.89442308 0.91698718 0.89442308        nan        nan
 0.91948718 0.89442308 0.91955128 0.89442308        nan        nan
 0.91698718 0.89442308 0.92705128 0.89442308        nan        nan
 0.92705128 0.89442308 0.92955128 0.89442308        nan        nan
 0.93455128 0.89442308 0.93705128 0.89442308        nan        nan
 0.93455128 0.89442308 0.94205128 0.89442308        nan        nan
 0.94205128 0.89442308 0.94205128 0.89442308        nan        nan
 0.94455128 0.89442308 0.94205128 0.89442308        nan        nan
 0.94705128 0.89442308 0.94705128 0.89442308        nan        nan
 0.94705128 0.89442308 0.94705128 0.89442308        nan        nan
 0.94448718 0.89442308 0.94705128 0.89442308        nan        nan
 0.94698718 0.89442308 0.94705128 0.89442308        nan        nan
 0.94705128 0.89442308 0.

In [7]:
y_pred = model.predict(X_test)
print("testing set")
print("accurcy: %f" % accuracy_score(y_test, y_pred))
print("precision: %f" % precision_score(y_test, y_pred, zero_division=0))
print("recall: %f" % recall_score(y_test, y_pred))
print("f1 scorce: %f" % f1_score(y_test, y_pred))
print("confusion matrix:\n", confusion_matrix(y_test, y_pred))
y_pred = model.predict(X_train)
print("\ntraining set")
print("accurcy: %f" % accuracy_score(y_train, y_pred))
print("precision: %f" % precision_score(y_train, y_pred, zero_division=0))
print("recall: %f" % recall_score(y_train, y_pred))
print("f1 scorce: %f" % f1_score(y_train, y_pred))
print("confusion matrix:\n", confusion_matrix(y_train, y_pred))

testing set
accurcy: 0.970760
precision: 0.981308
recall: 0.972222
f1 scorce: 0.976744
confusion matrix:
 [[ 61   2]
 [  3 105]]

training set
accurcy: 0.979899
precision: 0.980080
recall: 0.987952
f1 scorce: 0.984000
confusion matrix:
 [[144   5]
 [  3 246]]
