In [1]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split, GridSearchCV
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data = load_breast_cancer()
X, y = load_breast_cancer(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [3]:
from sklearn import svm
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

clf = svm.SVC()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print("testing set")
print("accurcy: %f" % accuracy_score(y_test, y_pred))
print("precision: %f" % precision_score(y_test, y_pred, zero_division=0))
print("recall: %f" % recall_score(y_test, y_pred))
print("f1 scorce: %f" % f1_score(y_test, y_pred))
print("confusion matrix:\n", confusion_matrix(y_test, y_pred))
y_pred = clf.predict(X_train)
print("\ntraining set")
print("accurcy: %f" % accuracy_score(y_train, y_pred))
print("precision: %f" % precision_score(y_train, y_pred, zero_division=0))
print("recall: %f" % recall_score(y_train, y_pred))
print("f1 scorce: %f" % f1_score(y_train, y_pred))
print("confusion matrix:\n", confusion_matrix(y_train, y_pred))

testing set
accurcy: 0.935673
precision: 0.907563
recall: 1.000000
f1 scorce: 0.951542
confusion matrix:
 [[ 52  11]
 [  0 108]]

training set
accurcy: 0.899497
precision: 0.869258
recall: 0.987952
f1 scorce: 0.924812
confusion matrix:
 [[112  37]
 [  3 246]]


In [5]:
clf = svm.SVC(kernel='linear')
param_grid = {'C': [0.01, 0.05, 0.1, 0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1,2,3,4,5,6,7,8,9,10,12,13,14,15,16,16.5,17,18]}
model = GridSearchCV(clf, param_grid=param_grid, scoring='accuracy', cv=10, n_jobs=-1)

model.fit(X_train, y_train)

print('Best Params:', model.best_params_)
y_pred = model.predict(X_test)
print("testing set")
print("accurcy: %f" % accuracy_score(y_test, y_pred))
print("precision: %f" % precision_score(y_test, y_pred, zero_division=0))
print("recall: %f" % recall_score(y_test, y_pred))
print("f1 scorce: %f" % f1_score(y_test, y_pred))
print("confusion matrix:\n", confusion_matrix(y_test, y_pred))
y_pred = model.predict(X_train)
print("\ntraining set")
print("accurcy: %f" % accuracy_score(y_train, y_pred))
print("precision: %f" % precision_score(y_train, y_pred, zero_division=0))
print("recall: %f" % recall_score(y_train, y_pred))
print("f1 scorce: %f" % f1_score(y_train, y_pred))
print("confusion matrix:\n", confusion_matrix(y_train, y_pred))

Best Params: {'C': 3}
testing set
accurcy: 0.976608
precision: 0.981481
recall: 0.981481
f1 scorce: 0.981481
confusion matrix:
 [[ 61   2]
 [  2 106]]

training set
accurcy: 0.967337
precision: 0.960938
recall: 0.987952
f1 scorce: 0.974257
confusion matrix:
 [[139  10]
 [  3 246]]


In [6]:
clf = svm.SVC(kernel='poly')
param_grid = {'C': [0.01, 0.05, 0.1, 0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1,2,3,4,5,6,7,8,9,10,12,13,14,15,16,16.5,17,18]}
model = GridSearchCV(clf, param_grid=param_grid, scoring='accuracy', cv=10, n_jobs=-1)

model.fit(X_train, y_train)

print('Best Params:', model.best_params_)
y_pred = model.predict(X_test)
print("testing set")
print("accurcy: %f" % accuracy_score(y_test, y_pred))
print("precision: %f" % precision_score(y_test, y_pred, zero_division=0))
print("recall: %f" % recall_score(y_test, y_pred))
print("f1 scorce: %f" % f1_score(y_test, y_pred))
print("confusion matrix:\n", confusion_matrix(y_test, y_pred))
y_pred = model.predict(X_train)
print("\ntraining set")
print("accurcy: %f" % accuracy_score(y_train, y_pred))
print("precision: %f" % precision_score(y_train, y_pred, zero_division=0))
print("recall: %f" % recall_score(y_train, y_pred))
print("f1 scorce: %f" % f1_score(y_train, y_pred))
print("confusion matrix:\n", confusion_matrix(y_train, y_pred))

Best Params: {'C': 8}
testing set
accurcy: 0.941520
precision: 0.922414
recall: 0.990741
f1 scorce: 0.955357
confusion matrix:
 [[ 54   9]
 [  1 107]]

training set
accurcy: 0.909548
precision: 0.890110
recall: 0.975904
f1 scorce: 0.931034
confusion matrix:
 [[119  30]
 [  6 243]]


In [7]:
clf = svm.SVC(kernel='rbf')
param_grid = {'C': [0.01, 0.05, 0.1, 0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1,2,3,4,5,6,7,8,9,10,12,13,14,15,16,16.5,17,18]}
model = GridSearchCV(clf, param_grid=param_grid, scoring='accuracy', cv=10, n_jobs=-1)

model.fit(X_train, y_train)

print('Best Params:', model.best_params_)
y_pred = model.predict(X_test)
print("testing set")
print("accurcy: %f" % accuracy_score(y_test, y_pred))
print("precision: %f" % precision_score(y_test, y_pred, zero_division=0))
print("recall: %f" % recall_score(y_test, y_pred))
print("f1 scorce: %f" % f1_score(y_test, y_pred))
print("confusion matrix:\n", confusion_matrix(y_test, y_pred))
y_pred = model.predict(X_train)
print("\ntraining set")
print("accurcy: %f" % accuracy_score(y_train, y_pred))
print("precision: %f" % precision_score(y_train, y_pred, zero_division=0))
print("recall: %f" % recall_score(y_train, y_pred))
print("f1 scorce: %f" % f1_score(y_train, y_pred))
print("confusion matrix:\n", confusion_matrix(y_train, y_pred))

Best Params: {'C': 4}
testing set
accurcy: 0.953216
precision: 0.938596
recall: 0.990741
f1 scorce: 0.963964
confusion matrix:
 [[ 56   7]
 [  1 107]]

training set
accurcy: 0.914573
precision: 0.896679
recall: 0.975904
f1 scorce: 0.934615
confusion matrix:
 [[121  28]
 [  6 243]]


In [8]:
clf = svm.SVC(kernel='sigmoid')
param_grid = {'C': [0.01, 0.05, 0.1, 0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1,2,3,4,5,6,7,8,9,10,12,13,14,15,16,16.5,17,18]}
model = GridSearchCV(clf, param_grid=param_grid, scoring='accuracy', cv=10, n_jobs=-1)

model.fit(X_train, y_train)

print('Best Params:', model.best_params_)
y_pred = model.predict(X_test)
print("testing set")
print("accurcy: %f" % accuracy_score(y_test, y_pred))
print("precision: %f" % precision_score(y_test, y_pred, zero_division=0))
print("recall: %f" % recall_score(y_test, y_pred))
print("f1 scorce: %f" % f1_score(y_test, y_pred))
print("confusion matrix:\n", confusion_matrix(y_test, y_pred))
y_pred = model.predict(X_train)
print("\ntraining set")
print("accurcy: %f" % accuracy_score(y_train, y_pred))
print("precision: %f" % precision_score(y_train, y_pred, zero_division=0))
print("recall: %f" % recall_score(y_train, y_pred))
print("f1 scorce: %f" % f1_score(y_train, y_pred))
print("confusion matrix:\n", confusion_matrix(y_train, y_pred))

Best Params: {'C': 0.5}
testing set
accurcy: 0.631579
precision: 0.633136
recall: 0.990741
f1 scorce: 0.772563
confusion matrix:
 [[  1  62]
 [  1 107]]

training set
accurcy: 0.643216
precision: 0.638243
recall: 0.991968
f1 scorce: 0.776730
confusion matrix:
 [[  9 140]
 [  2 247]]
